# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'seat-code' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'Polyline', '~> 4.0'
  pod 'SwiftLint'
  pod 'RealmSwift'
	
  # Pods for seat-code

  target 'seat-codeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'seat-codeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
